#pragma once
// ─────────────────────────────────────────────────────────────────────────────
// src/order_types.h  —  Core HFT data types
//
// Design notes:
//  * Price stored as int64 ticks (fixed-point) — avoids float comparison bugs
//  * alignas(64) on Order — one order per cache line, prevents false sharing
//  * OrderId starts at 1 (0 = invalid sentinel)
// ─────────────────────────────────────────────────────────────────────────────
#include <cstdint>

using OrderId   = std::uint64_t;
using Price     = std::int64_t;   // price in ticks (e.g. $100.05 -> 10005 if tick=0.01)
using Qty       = std::uint32_t;
using Timestamp = std::int64_t;   // nanoseconds since epoch

static constexpr OrderId kInvalidOrderId = 0;

enum class Side : std::uint8_t {
    BID = 0,  // buy side
    ASK = 1,  // sell side
};

enum class OrderType : std::uint8_t {
    LIMIT  = 0,  // execute at specified price or better
    MARKET = 1,  // execute immediately at best available price
};

enum class OrderStatus : std::uint8_t {
    NEW       = 0,
    PARTIAL   = 1,  // partially filled, still active
    FILLED    = 2,  // fully filled
    CANCELLED = 3,
    REJECTED  = 4,  // e.g. insufficient liquidity for MARKET
};

// alignas(64): one Order per L1 cache line.
// sizeof(Order) must be exactly 64 bytes.
struct alignas(64) Order {
    OrderId      id{kInvalidOrderId};
    Price        price{0};
    Qty          qty{0};
    Qty          filled_qty{0};
    Timestamp    timestamp_ns{0};
    Side         side{Side::BID};
    OrderType    type{OrderType::LIMIT};
    OrderStatus  status{OrderStatus::NEW};
    std::uint8_t _pad[64
        - sizeof(OrderId)
        - sizeof(Price)
        - 2 * sizeof(Qty)
        - sizeof(Timestamp)
        - 3 * sizeof(std::uint8_t)]{};

    [[nodiscard]] bool is_active()   const noexcept {
        return status == OrderStatus::NEW || status == OrderStatus::PARTIAL;
    }
    [[nodiscard]] Qty  remaining()   const noexcept { return qty - filled_qty; }
};
static_assert(sizeof(Order)  == 64, "Order must be exactly one cache line");
static_assert(alignof(Order) == 64, "Order must be cache-line aligned");

// Execution report generated by the matching engine
struct Trade {
    OrderId   maker_id{kInvalidOrderId};  // resting (passive) order
    OrderId   taker_id{kInvalidOrderId};  // aggressive order
    Price     price{0};
    Qty       qty{0};
    Timestamp timestamp_ns{0};

    [[nodiscard]] bool valid() const noexcept {
        return maker_id != kInvalidOrderId && taker_id != kInvalidOrderId && qty > 0;
    }
};

// L2 price-level snapshot
struct PriceLevel {
    Price price{0};
    Qty   qty{0};    // aggregate qty at this level
    int   count{0};  // number of orders at this level
};
